### ISSUE TITLE
Tony Changes Unintended Behaviors

### ISSUE THREAD

**Issue by ZASnow** [ColeT25/CoolerMathGames#20]
On the header on games, it prompts you to sign in again even if you are already signed in whenever you go to a new game. Additionally, the header display doesn't seem to be working properly on the score submit screen.

**Comment by ColeT25** [comment]
This should be fixed now, the header.html page was referencing a non-existent CSS page. I changed it to one that does exist, and the header started showing up on each page. I also changed the header so that the links all work correctly, and I made it so it displays if you are logged in correctly on each page. The changes that fixed this can be found [here](https://github.com/ColeT25/CoolerMathGames/commit/24575ca0fbca3c0a6d0b458a51429ab54e338a09)

**Comment by ColeT25** [comment]
There still seems to be some minor issues with everything lining up correctly in the header, and the credits page explodes if you try to add the header to it. But this bug is fixed now
